# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name cppfor
#' @title Fast Implementation of Dynamic Algorithm Using C++
#'
#' @description This function creates an equivalent of the nested for loop in
#' the dynamic algorithm for a faster implementation using C++ code instead of
#' R code.
#'
#' @param n The number of available objects to place in the knapsack
#' @param w The numeric weight limit of the knapsack
#' @param w A numeric vector which contains the weights from data.frame 'x'
#' @param v A numeric vector which contains the values from data.frame 'x'
#' @param mat A zero matrix with (n + 1) rows and (W + 1) columns, with n
#' being the number of available objects and W being the weight limit of the
#' knapsack
#' @param mem A zero data.frame with one column and (n + 1) rows
#'
#'
NULL

cppfor <- function(n, W, w, v, mat, mem) {
    .Call('_knapsack_cppfor', PACKAGE = 'knapsack', n, W, w, v, mat, mem)
}

